### ISSUE TITLE
org.omg removed from JDK 11

### ISSUE THREAD

**Issue by KSRandom** [jppf-grid/JPPF#7]
### Observed behavior

It is not possible to build with JDK 11 or newer due to the absence of org.omg.CORBA_2_3.portable.InputStream.

You can see it's containing package is included in the JDK 10 documentation:
https://docs.oracle.com/javase/10/docs/api/overview-tree.html

But was removed in the JDK 11 documentation: https://docs.oracle.com/en/java/javase/11/docs/api/overview-tree.html

### Expected behavior

Expect to be able to build. In the short term we may want to indicate you need between Java 8 and Java 10.

### Environment information

- **JPPF version(s):** [bdbf39be8f19ea26e349417655cd619f9073895e](https://github.com/jppf-grid/JPPF/commit/bdbf39be8f19ea26e349417655cd619f9073895e)
- **JDK version:** openjdk 13.0.1 2019-10-15
- **OS and version:** Windows 10

### How to reproduce

1. Install JDK 11 or newer and ant
2. Clone the Repo
3. `ant build`

PS D:\JPPF> ant build
Buildfile: D:\JPPF\build.xml

build:
     [echo] Building JPPF (without installer)

clean:

init:
    [mkdir] Created dir: D:\JPPF\jmxremote\classes
    [mkdir] Created dir: D:\JPPF\jmxremote\build

compile:
    [javac] Compiling 109 source files to D:\JPPF\jmxremote\classes
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:70: error: package org.omg.CORBA.portable does not exist
    [javac] import org.omg.CORBA.portable.BoxedValueHelper;
    [javac]                              ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:76: error: package org.omg.CORBA_2_3.portable does not exist
    [javac] public class ProxyInputStream extends org.omg.CORBA_2_3.portable.InputStream {
    [javac]                                                                 ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:80: error: package org.omg.CORBA.portable does not exist
    [javac]   protected final org.omg.CORBA.portable.InputStream in;
    [javac]                                         ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:86: error: package org.omg.CORBA.portable does not exist
    [javac]   public ProxyInputStream(final org.omg.CORBA.portable.InputStream in) {
    [javac]                                                       ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:221: error: package org.omg.CORBA does not exist
    [javac]   public org.omg.CORBA.Object read_Object() {
    [javac]                       ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:226: error: cannot find symbol
    [javac]   public TypeCode read_TypeCode() {
    [javac]          ^
    [javac]   symbol:   class TypeCode
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:231: error: cannot find symbol
    [javac]   public Any read_any() {
    [javac]          ^
    [javac]   symbol:   class Any
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:237: error: cannot find symbol
    [javac]   public Principal read_Principal() {
    [javac]          ^
    [javac]   symbol:   class Principal
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:252: error: cannot find symbol
    [javac]   public Context read_Context() {
    [javac]          ^
    [javac]   symbol:   class Context
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:258: error: package org.omg.CORBA does not exist
    [javac]   public org.omg.CORBA.Object read_Object(final java.lang.Class clz) {
    [javac]                       ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:263: error: cannot find symbol
    [javac]   public ORB orb() {
    [javac]          ^
    [javac]   symbol:   class ORB
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:279: error: cannot find symbol
    [javac]   public Serializable read_value(final BoxedValueHelper factory) {
    [javac]                                        ^
    [javac]   symbol:   class BoxedValueHelper
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:308: error: package org.omg.CORBA_2_3.portable does not exist
    [javac]   protected org.omg.CORBA_2_3.portable.InputStream narrow() {
    [javac]                                       ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:317: error: package org.omg.CORBA.portable does not exist
    [javac]   public org.omg.CORBA.portable.InputStream getProxiedInputStream() {
    [javac]                                ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:69: error: package org.omg.CORBA does not exist
    [javac] import org.omg.CORBA.*;
    [javac] ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:90: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:95: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:100: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:105: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:110: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:115: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:120: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:125: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:130: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:135: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:140: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:145: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:150: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:155: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:160: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:165: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:170: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:175: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:180: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:185: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:190: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:195: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:200: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:205: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:210: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:215: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:220: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:225: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:230: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:235: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:241: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:246: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:251: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:256: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:262: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:267: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:272: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:278: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:284: error: name clash: class ProxyInputStream has two methods with the same erasure, yet neither overrides the other
    [javac]   public Serializable read_value(final String rep_id) {
    [javac]                       ^
    [javac]   first method:  read_value(BoxedValueHelper) in ProxyInputStream
    [javac]   second method: read_value(Class) in ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:283: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:289: error: name clash: class ProxyInputStream has two methods with the same erasure, yet neither overrides the other
    [javac]   public Serializable read_value(final Serializable value) {
    [javac]                       ^
    [javac]   first method:  read_value(BoxedValueHelper) in ProxyInputStream
    [javac]   second method: read_value(Class) in ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:288: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:293: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:298: error: method does not override or implement a method from a supertype
    [javac]   @Override
    [javac]   ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:309: error: package org.omg.CORBA_2_3.portable does not exist
    [javac]     if (in instanceof org.omg.CORBA_2_3.portable.InputStream) return (org.omg.CORBA_2_3.portable.InputStream) in;
    [javac]                                                 ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:309: error: package org.omg.CORBA_2_3.portable does not exist
    [javac]     if (in instanceof org.omg.CORBA_2_3.portable.InputStream) return (org.omg.CORBA_2_3.portable.InputStream) in;
    [javac]                                                                                                 ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\internal\ProxyInputStream.java:310: error: cannot find symbol
    [javac]     throw new NO_IMPLEMENT();
    [javac]               ^
    [javac]   symbol:   class NO_IMPLEMENT
    [javac]   location: class ProxyInputStream
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\security\TLSServerHandler.java:397: warning: [removal] X509Certificate in javax.security.cert has been deprecated and marked for removal
    [javac]         final X509Certificate[] certificate = session.getPeerCertificateChain();
    [javac]               ^
    [javac] D:\JPPF\jmxremote\src\java\com\sun\jmx\remote\opt\security\TLSServerHandler.java:397: warning: [removal] getPeerCertificateChain() in SSLSession has been deprecated and marked for removal
    [javac]         final X509Certificate[] certificate = session.getPeerCertificateChain();
    [javac]                                                      ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 62 errors
    [javac] 2 warnings

**Comment by lolocohen** [comment]
Thanks for the report. Thankfully, these issues are easily reproducible. The fix I'm proposing :
 - [ ] remove the `jmxremote` module altogether, it is no longer used, and I can't see any reason to keep it. Removing it will resolve most of the compile errors
 - [ ] there other other modules with compile errors with jdk 11+ :  `JPPF` (for the `@exclude` javadoc doclet) and `jca-client`. For those I can at least temporarily make the problem go away by either using reflixive calls for classes no longer present or by adding conditions in the build based on the jdk version

**Comment by lolocohen** [comment]
Resolved in PR #8
